name: API Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Newman
        run: npm install -g newman

      - name: Run Checkout API tests
        run: |
          newman run checkout \
            --iteration-data checkout_data.csv

      - name: Run Invoices API tests
        run: |
          newman run invoices \
            --iteration-data invoice_id.csv

      - name: Run Favorites API tests
        run: |
          newman run favorites \s
            --iteration-data product_id.csv
