name: API Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Load environment variables
        run: |
          echo "Loading .env variables..."
          cp env.json .env

      - name: Run Checkout API tests
        run: |
          echo "Running checkout API tests..."
          node checkout --data checkout_data.csv

      - name: Run Invoice API tests
        run: |
          echo "Running invoices API tests..."
          node invoices --data invoice_id.csv

      - name: Run Favorites API tests
        run: |
          echo "Running favorites API tests (linked with product_id.csv)..."
          node favorites --data product_id.csv
